In [1]:
!pip install numpy --quiet

In [2]:
import numpy as np

NumPy is a low-level library written in C for high-level mathematical functions. NumPy cleverly overcomes the problem of running slower algorithms on Python using multidimensional arrays and functions that operate on arrays. Any algorithm can then be expressed as a function on arrays, allowing the algorithms to be run quickly.

Applications of NumPy

- A powerful N-dimensional array object.
- Sophisticated functions.
- Tools for integrating C/C++ and Fortran code.
- Useful linear algebra, Fourier transforms,and random number capabilities.

# Creating NumPy Arrays

1. np.array() // 1-D and 2-D arrays.
2. np.zeros/ones/empty/random() functions.
3. np.arange()
4. np.linspace()
5. Copy()
6. np.dentity()

In [3]:
arr1 = np.array([1,2,3,4,5]) #one dimension array.

In [4]:
type(arr1) # the type function returns the type of the object.

numpy.ndarray

In [5]:
arr2 = np.array([[1,2,3],[6,7,8]]) #two dimension array.
arr2

array([[1, 2, 3],
       [6, 7, 8]])

In [6]:
arr3 = np.zeros((2,3)) #the size of the array is passed as a tuple.
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
arr4 = np.ones((3,4))
arr4

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
arr5 = np.random.rand(3,4)
arr5

array([[0.05200743, 0.92355079, 0.96203423, 0.55616653],
       [0.95999899, 0.16829437, 0.24683913, 0.68750265],
       [0.03155347, 0.05837933, 0.9884128 , 0.82765588]])

In [9]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [10]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(5,16)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [12]:
np.arange(5,16,2)

array([ 5,  7,  9, 11, 13, 15])

In [13]:
np.linspace(10,20,3)

array([10., 15., 20.])

In [14]:
arr6 = arr1.copy()
arr6

array([1, 2, 3, 4, 5])

# Properties and Arrtributes

1. Shape
2. nDim
3. Size
4. Itemsize
5. Dtype
6. astype()

In [15]:
arr9 = np.array([[[1,2],[3,4]],[[5,6],[7,9]]]) # this is a 3d matrix and its dimensions can be found by ndim method.
arr9

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 9]]])

In [16]:
arr9.shape

(2, 2, 2)

In [17]:
arr9.ndim

3

In [18]:
arr2

array([[1, 2, 3],
       [6, 7, 8]])

In [19]:
arr2.ndim

2

In [20]:
arr1.ndim

1

In [21]:
arr1

array([1, 2, 3, 4, 5])

In [22]:
arr1.size # prints number of elements inside the array.

5

In [23]:
arr2.size

6

In [24]:
arr9.size

8

In [25]:
print(arr3)
arr3.itemsize # prints the size of element. like this is a float so 8 bytes

[[0. 0. 0.]
 [0. 0. 0.]]


8

In [26]:
arr9.dtype

dtype('int64')

In [27]:
#we can also change the data type by using a method called astype

In [28]:
arr9.astype('int16')

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 9]]], dtype=int16)

In [29]:
arr9.itemsize

8

## List vs Array

1. Faster
2. Convenient
3. Less Memory

In [30]:
import sys
lista = range(100)
nparr = np.arange(100)

In [31]:
print(sys.getsizeof(98)*len(lista))

2800


In [32]:
print(nparr.itemsize*nparr.size) # here we can see that we are already saving a lot of space by using numpy arrays.

800


In [33]:
x = range(1000)
y = range(1000,2000)

In [34]:
%%time
c = [x+y for x,y in zip(x,y)]

CPU times: user 86 µs, sys: 33 µs, total: 119 µs
Wall time: 184 µs


In [35]:
a = np.arange(1000)
b = np.arange(1000,2000)

In [36]:
%%time
c = a + b

CPU times: user 33 µs, sys: 37 µs, total: 70 µs
Wall time: 105 µs


## Indexing, Slicing and Iteration

In [37]:
arr12 = np.arange(24).reshape(6,4)

In [38]:
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [39]:
arr12[2]

array([ 8,  9, 10, 11])

In [40]:
arr12[2,3]

11

In [41]:
arr12[1:3,2:4]

array([[ 6,  7],
       [10, 11]])

In [42]:
arr12[:,1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18],
       [21, 22]])

In [43]:
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [44]:
for i in arr12:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [45]:
for i in np.nditer(arr12):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


## Numpy Operations

In [46]:
arr13 = np.array([1,2,3,4,5,6])
arr14 = np.array([4,5,6,7,8,9])

In [47]:
arr13-arr14

array([-3, -3, -3, -3, -3, -3])

In [48]:
arr13*arr14

array([ 4, 10, 18, 28, 40, 54])

In [49]:
arr13*2

array([ 2,  4,  6,  8, 10, 12])

In [50]:
arr13>3

array([False, False, False,  True,  True,  True])

In [51]:
arr15 = np.arange(6).reshape(2,3)
arr16 = np.arange(6,12).reshape(3,2)

In [52]:
arr15.dot(arr16)

array([[ 28,  31],
       [100, 112]])

In [53]:
## Some Basic Operations

In [54]:
arr16

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [66]:
arr16.min()

6

In [67]:
print(arr16.min(axis=0))

[6 7]


In [68]:
arr16.min(axis=1)

array([ 6,  8, 10])

In [69]:
arr16.max()

11

In [71]:
arr16.sum()

51

In [73]:
arr16.mean()

8.5

In [74]:
arr16.std()

1.707825127659933

In [77]:
np.median(arr16)

8.5

In [76]:
np.sin(arr16)

array([[-0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849],
       [-0.54402111, -0.99999021]])

In [78]:
np.exp(arr16)

array([[  403.42879349,  1096.63315843],
       [ 2980.95798704,  8103.08392758],
       [22026.46579481, 59874.1417152 ]])

In [79]:
np.sqrt(arr16)

array([[2.44948974, 2.64575131],
       [2.82842712, 3.        ],
       [3.16227766, 3.31662479]])

## Reshaping Numpy Arrays
1. Ravel
2. Reshape
3. Transpose
4. Stacking
5. Splitting

In [80]:
arr16.ndim

2

In [82]:
arr16.ravel() # Takes higher dimension arrays to a single dimension array without loosing any information.

array([ 6,  7,  8,  9, 10, 11])

In [85]:
arr16.reshape(2,3)

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [87]:
arr16.transpose()

array([[ 6,  8, 10],
       [ 7,  9, 11]])

In [90]:
arr15

array([[0, 1, 2],
       [3, 4, 5]])

In [91]:
arr16

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [92]:
arr16.dot(arr15)

array([[21, 34, 47],
       [27, 44, 61],
       [33, 54, 75]])

In [96]:
arr17 = np.array([[2,4,5],[7,5,9]])
arr17

array([[2, 4, 5],
       [7, 5, 9]])

In [98]:
np.hstack((arr15,arr17))

array([[0, 1, 2, 2, 4, 5],
       [3, 4, 5, 7, 5, 9]])

In [99]:
np.vstack((arr15,arr17))

array([[0, 1, 2],
       [3, 4, 5],
       [2, 4, 5],
       [7, 5, 9]])

In [100]:
arr15

array([[0, 1, 2],
       [3, 4, 5]])

In [101]:
np.hsplit(arr15,3)

[array([[0],
        [3]]),
 array([[1],
        [4]]),
 array([[2],
        [5]])]

In [103]:
np.vsplit(arr15,2)

[array([[0, 1, 2]]), array([[3, 4, 5]])]

## Fancy Indexing

In [105]:
arr18 = np.arange(24).reshape(6,4)

In [106]:
arr18

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [108]:
arr18[[0,2,4]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [16, 17, 18, 19]])

## Indexing using Boolean Arrays

In [116]:
arr19 = np.random.randint(low=1,high=100,size=20).reshape(4,5)

In [117]:
arr19

array([[19,  2, 19, 73, 75],
       [87,  2,  2, 18, 26],
       [84, 15, 47, 94, 87],
       [ 8, 19, 59, 56, 41]])

In [119]:
arr19>50

array([[False, False, False,  True,  True],
       [ True, False, False, False, False],
       [ True, False, False,  True,  True],
       [False, False,  True,  True, False]])

In [126]:
arr19[(arr19>50)]

array([73, 75, 87, 84, 94, 87, 59, 56])

In [127]:
arr19[(arr19>50) & (arr19%2 != 0)]

array([73, 75, 87, 87, 59])

In [128]:
arr19[(arr19>50) & (arr19%2 != 0)] = 0

In [129]:
arr19

array([[19,  2, 19,  0,  0],
       [ 0,  2,  2, 18, 26],
       [84, 15, 47, 94,  0],
       [ 8, 19,  0, 56, 41]])

## Broadcasting

The ability of Numpy arrays to perform arithmetic operations on arrays of dissimilar sizes, by broadcasting the smaller array to match the size.

In [136]:
a1 = np.arange(8).reshape(2,4)
a2 = np.arange(8,12).reshape(1,4)

In [137]:
a1+a2

array([[ 8, 10, 12, 14],
       [12, 14, 16, 18]])

In [139]:
a3 = np.arange(9).reshape(3,3)
a4 = np.array([1])

In [141]:
a3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [142]:
a3+a4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Important Numpy functions

In [188]:
np.random.random()

0.1073653029524273

In [189]:
np.random.seed(1)
np.random.random()

0.417022004702574

In [190]:
np.random.uniform(3,10)

8.042271454095108

In [191]:
np.random.uniform(3,10,3)

array([3.00080062, 5.11632801, 4.02729124])

In [192]:
np.random.randint(1,10)

1

In [200]:
a = np.random.randint(1,10,10)

In [201]:
a.min()

2

In [202]:
a.argmin() #gives the index of minimum value

8

In [203]:
a.max()

8

In [204]:
a.argmax()

6

In [205]:
a[a.argmax()]

8

In [206]:
a

array([5, 6, 3, 5, 3, 5, 8, 8, 2, 8])

In [207]:
a[(a%2 != 0)] = -1

In [208]:
a

array([-1,  6, -1, -1, -1, -1,  8,  8,  2,  8])

In [212]:
a = np.random.randint(1,10,10)
a

array([9, 8, 4, 7, 6, 2, 4, 5, 9, 2])

In [214]:
np.sort(a)

array([2, 2, 4, 4, 5, 6, 7, 8, 9, 9])

In [219]:
np.percentile(a,50)

5.5